#!/bin/bash

# ===============================================================================================
# Docker functions
# ===============================================================================================

ds() {
  case $1 in
  clean)
    docker-sync-stack clean
    ;;
  start)
    # Container ids
    local api="shortstackapi_web_1"
    local asterisk="asterisk_web_1"
    local dealkit="dealkit_web_1"
    local designer="shortstackdesigner_web_1"
    local emails="shortstackemails_web_1"
    local es="docker.elastic.co"
    local mysql="dockermysql_db_1"
    local server="shortstackserver_web_1"
    local shortstack2="shortstack2_web_1"
    local shortstack="shortstack_web_1"
    local style="shortstackstyle_web_1"

    local dir=${PWD##*/}
    declare -a ssdeps=()

    case $dir
      shortstackadmin)
        ssdeps=($designer $dealkit)
        ;;
      asterisk)
         ssdeps=($mysql $es)
         ;;
       dealkit)
         ssdeps=($server $shortstack $shortstack2)
         ;;
       shortstack)
         ssdeps=($api $emails $style $asterisk)
         ;;
       shortstack2)
         ssdeps=($api $emails $style $asterisk)
         ;;
       shortstackapi)
         ssdeps=($mysql $es)
         ;;
       shortstackdesigner)
         ssdeps=($server $shortstack $shortstack2)
         ;;
       shortstackemails)
         ssdeps=($mysql $es)
         ;;
       shortstackserver)
         ssdeps=($api $emails $style $asterisk)
         ;;
       shortstackstyle)
         ssdeps=($mysql $es)
         ;;

    local all="yes"
    for ssdep in $ssdeps[@]; do
      # Set the all flag to no if there is a missing container
      if [ -z "$(docker ps | grep "$ssdep")" ]; then
        echo "$ssdep not running"
        all="no"
      fi
    done

    # If all dependent containers are running
    if [ "$all" = "yes" ]; then
      ds clean
      if [ -f tmp/unicorn.pid ]; then
        rm tmp/unicorn.pid
        dcdev run web rm tmp/unicorn.pid
      fi

      docker-sync-stack start
    else
      sleep 1
      echo ""
      ds start
    fi
    ;;
  stop)
    docker-sync-stack stop
    ;;
  stopall)
    docker stop $(docker ps -a -q)
    # docker kill $(docker ps -q)
    ;;
  bash)
    if [[ $1 =~ '^[0-9]+$' ]]; then
      local CONTAINER=$(docker ps | grep $1)
    else
      local CONTAINER=$(docker-compose ps | grep foreman)
    fi

    if [[ $CONTAINER ]]; then
      docker exec -it $(echo $CONTAINER | perl -lne 'print $& if /^[^\s]+/') bash
    else
      echo "Container not found"
    fi
    ;;
  restart)
    ds clean
    ds start
    ;;
  esac
}

db() {
  case $1
    backup)
      dbmgr mysql backup shortstack_development --host 0.0.0.0 -P 3306 -p ~/Documents/shortstack_apps/db_backups
      ;;
    restore)
      dbmgr mysql restore shortstack_development -P 3306 --host 0.0.0.0 -p ~/Documents/shortstack_apps/db_backups
      ;;
  esac
}
