#!/bin/zsh

alias mk=minikube
alias kb=kubectl

function mk-start() {
  # Start minikube
  minikube start --vm-driver=hyperkit

  # Switch to the minikube context
  kb config use-context minikube
}

function mk-stop() {
  minikube stop
}
